### ISSUE TITLE
Feature flags are enabling platform features not app features

### ISSUE THREAD

**Issue by gberche-orange** [cloudfoundry/summit-training-classes#12]
As part of the route section, and blue/green deployment among version 1.0 and 1.1 or an application.

https://github.com/cloudfoundry/summit-training-classes/blob/095d4d08fc757987926587c717bd800c1dbc4abc/basics/site/content/labs/routes.md#L71 mentions the following
> Use feature flags instead of ENV vars for new features

This implictly implies that CF feature flags are a way to turn on feature flags in applications instead of relying on enviroment variables or other app specific mechanism such as external configuration (spring cloud config server).

However, CF feature flags are a way to turn on Cf features (usually by pass admins) and not a way for app teams to turn on/off their own app features.

It might be more appropriate to point to app-specific mechanism to support feature flags such as libraries such as https://www.togglz.org/ or spring cloud config server

**Comment by DanielJonesEB** [comment]
Cheers @gberche-orange - we're delivering this course on Friday, so I'll sort that out this week
